### ISSUE TITLE
Enhancement: Better Memory Handling

### ISSUE THREAD

**Issue by Raltyro** [EyeDaleHim/Crow-Engine#18]
Self-Explanatory

Also maybe use FlxAnimate for most of the characters? but i know that stuff doesn't fully work yet for transform using Matrix3D

**Comment by SwickTheGreat** [comment]
i wanna use FlxAnimate so badly but i'm getting stuck on how to implement it

**Comment by Cheemsandfriends** [comment]
>  know that stuff doesn't fully work yet for transform using Matrix3D

@Raltyro, FlxAnimate doesn't support 2.5 transformations due to OpenFL not even supporting it (by normal means at least), it would be a matter of either make a PR about supporting 3D matrices on OpenFL, or use the OpenGLRenderer to make its own rendering system? I don't even know yet since I'm also working on a way that can support filters and in a way that can be used in HaxeFlixel like FlxSprite.

> i wanna use FlxAnimate so badly but i'm getting stuck on how to implement it

@SwickTheGreat, If you have any issues with FlxAnimate, you can always contact me thro Discord, it's somewhere on the README.

**Comment by SwickTheGreat** [comment]
@Cheemsandfriends, I can't seem to find your discord, but I do have a couple of questions about FlxAnimate.

**Comment by Cheemsandfriends** [comment]
> @Cheemsandfriends, I can't seem to find your discord, but I do have a couple of questions about FlxAnimate.

It's on the [`Support`](https://github.com/Dot-Stuff/flxanimate#support) tab!
It's `Miss Muffin#8930`.

**Comment by Raltyro** [comment]
> > know that stuff doesn't fully work yet for transform using Matrix3D
> 
> @Raltyro, FlxAnimate doesn't support 2.5 transformations due to OpenFL not even supporting it (by normal means at least), it would be a matter of either make a PR about supporting 3D matrices on OpenFL, or use the OpenGLRenderer to make its own rendering system? I don't even know yet since I'm also working on a way that can support filters and in a way that can be used in HaxeFlixel like FlxSprite.
> 
> > i wanna use FlxAnimate so badly but i'm getting stuck on how to implement it
> 
> @SwickTheGreat, If you have any issues with FlxAnimate, you can always contact me thro Discord, it's somewhere on the README.

iirc, you can render textures with custom vertices in FlxCamera API, i forgot what functions is it
